CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    college_id INT NOT NULL,
    department_id INT NOT NULL,
    assigned_by_id INT NOT NULL,
    assigned_to_id INT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    deadline DATETIME NOT NULL,
    priority ENUM('Low', 'Medium', 'High', 'Critical') DEFAULT 'Medium',
    task_type ENUM('Academic', 'Event', 'Research', 'Administrative', 'Examination', 'Documentation', 'Other') DEFAULT 'Other',
    status ENUM('Draft', 'Assigned', 'Broadcasted', 'Accepted', 'In Progress', 'Submitted', 'Under Review', 'Approved', 'Rejected', 'Rework Required', 'Completed', 'Declined', 'Expired') DEFAULT 'Assigned',
    assignment_mode ENUM('individual', 'broadcast', 'group') DEFAULT 'individual',
    assigned_at TIMESTAMP NULL,
    accepted_at TIMESTAMP NULL,
    submitted_at TIMESTAMP NULL,
    reviewed_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    declined_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
